repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0  # Актуальная версия black
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0  # Актуальная версия flake8
    hooks:
      - id: flake8