version: "3.9"

services:
  tests:
    build: .
    container_name: api_tests
    volumes:
      - ./allure-results:/app/allure-results  # Монтируем папку для отчетов
    environment:
      - CI=true  # Переменная для GitHub Actions
    command: >
      sh -c "poetry install && poetry run pytest --alluredir=allure-results"